version: '3.5'
services:
  web:
    image: steveltn/https-portal:1
    container_name: web
    restart: always
    volumes:
      - ./nginx/ssl_certs:/var/lib/https-portal
      - ./nginx/conf/mysite_nginx.conf:/etc/nginx/conf.d/mysite_nginx.conf
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./src/static:/static
    ports:
      - '80:80'
      - '443:443'
    environment:
      DOMAINS: 'vccmarsh.link -> http://web:8080/'
      STAGE: 'staging'
    depends_on:
      - django
  django:
    build: ./django
    container_name: django
    volumes:
      - ./src:/code
    expose:
      - '8001'
    command: uwsgi --socket :8001 --module mysite.wsgi
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: db
    volumes:
      - ./db/dbdata:/var/lib/postgresql/data
    expose:
      - '5432'
    environment:
      - POSTGRES_USER=hogehoge
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=testDB